# NOTE: Generated By HttpRunner v3.1.7
# FROM: har\addTable.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAddtable(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login.html")
            .get("http://partner.dev.sedsy.com/login.html")
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Cache-Control": "max-age=0",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "If-Modified-Since": "Thu, 24 Mar 2022 06:14:39 GMT",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 304)
        ),
        Step(
            RunRequest("/captcha.jpg")
            .get("http://partner.dev.sedsy.com/captcha.jpg")
            .with_params(**{"uuid": "48096430472196030941443943523500"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/login.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/jpeg")
        ),
        Step(
            RunRequest("/partner/login")
            .post("http://partner.dev.sedsy.com/partner/login")
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Content-Length": "83",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "null",
                    "requestId": "2022032415230373854685",
                    "Origin": "http://partner.dev.sedsy.com",
                    "Referer": "http://partner.dev.sedsy.com/login.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .with_data(
                {
                    "username": "13311111110",
                    "password": "123456",
                    "captcha": "",
                    "uuid": "48096430472196030941443943523500",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.versionType", "CHAIN")
            .assert_equal("body.code", 0)
            .assert_equal("body.expire", 43200)
            .assert_equal("body.token", "24c7eadf81ca7de570d3f861814cd238")
        ),
        Step(
            RunRequest("/captcha.jpg")
            .get("http://partner.dev.sedsy.com/captcha.jpg")
            .with_params(**{"uuid": "05305605795194474011789664570352"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/login.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/jpeg")
        ),
        Step(
            RunRequest("/partner/partnermenu/nav")
            .get("http://partner.dev.sedsy.com/partner/partnermenu/nav")
            .with_params(**{"_": "1648106587387"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152307403783841",
                    "Referer": "http://partner.dev.sedsy.com/index.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.storeType", 1)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/partner/user/info")
            .get("http://partner.dev.sedsy.com/partner/user/info")
            .with_params(**{"_": "1648106587388"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152307403783841",
                    "Referer": "http://partner.dev.sedsy.com/index.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/partner/user/nav")
            .get("http://partner.dev.sedsy.com/partner/user/nav")
            .with_params(**{"_": "1648106587389"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152307403783841",
                    "Referer": "http://partner.dev.sedsy.com/index.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
            .assert_equal("body.navInfo", "便利店总部")
        ),
        Step(
            RunRequest("/depot/listStoreUnReadMsg")
            .get("http://partner.dev.sedsy.com/depot/listStoreUnReadMsg")
            .with_params(**{"_": "1648106587390"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152307403783841",
                    "Referer": "http://partner.dev.sedsy.com/index.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "没有权限，请联系管理员授权")
            .assert_equal("body.code", 500)
        ),
        Step(
            RunRequest("/partner/charts/statistics.json")
            .post("http://partner.dev.sedsy.com/partner/charts/statistics.json")
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Content-Length": "0",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "Content-Type": "application/json",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152307777000684",
                    "Origin": "http://partner.dev.sedsy.com",
                    "Referer": "http://partner.dev.sedsy.com/modules/welcome/partner_welcome.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.orders_m", 0)
            .assert_equal("body.refund_price_d", 0.0)
            .assert_equal("body.sum_price_d", 0.0)
            .assert_equal("body.recharge_prices_m", 0.0)
            .assert_equal("body.code", 0)
            .assert_equal("body.recharge_prices_d", 0.0)
            .assert_equal("body.refund_price_m", 0.0)
            .assert_equal("body.refund_orders_d", 0)
            .assert_equal("body.orders_d", 0)
            .assert_equal("body.sum_price_m", 0.0)
            .assert_equal("body.type", "2")
            .assert_equal("body.refund_orders_m", 0)
        ),
        Step(
            RunRequest("/table/query")
            .get("http://partner.dev.sedsy.com/table/query")
            .with_params(
                **{
                    "page": "1",
                    "limit": "10",
                    "tableCode": "",
                    "tableStatus": "",
                    "box": "",
                    "_": "1648106592992",
                }
            )
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152312995859507",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/box/boxes")
            .get("http://partner.dev.sedsy.com/box/boxes")
            .with_params(**{"_": "1648106592993"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152312995859507",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/fileUpload/getImg")
            .get("http://partner.dev.sedsy.com/fileUpload/getImg")
            .with_params(**{"fdfsId": "", "token": "24c7eadf81ca7de570d3f861814cd238"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/fileUpload/getImg")
            .get("http://partner.dev.sedsy.com/fileUpload/getImg")
            .with_params(
                **{"fdfsId": "undefined", "token": "24c7eadf81ca7de570d3f861814cd238"}
            )
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/fileUpload/getImg")
            .get("http://partner.dev.sedsy.com/fileUpload/getImg")
            .with_params(
                **{
                    "fdfsId": "group1/M00/01/93/wKgBsGIrE0aAK3JvAADe3H7fOh43932678",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                }
            )
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/jpg")
        ),
        Step(
            RunRequest("/fileUpload/getImg")
            .get("http://partner.dev.sedsy.com/fileUpload/getImg")
            .with_params(
                **{
                    "fdfsId": "group1/M00/01/93/wKgBsGIrADaAEsXAAAB2nLPcJRE7879665",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                }
            )
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/jpg")
        ),
        Step(
            RunRequest("/table/add")
            .post("http://partner.dev.sedsy.com/table/add")
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Content-Length": "141",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "Content-Type": "application/json",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152312995859507",
                    "Origin": "http://partner.dev.sedsy.com",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .with_json(
                {
                    "tableCode": "BBB",
                    "tableStatus": 1,
                    "tableType": 1,
                    "box": "824241541986373633",
                    "repastStatus": 2,
                    "maxCustomer": "50",
                    "codeUrl": "",
                    "minPrice": "06",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/table/query")
            .get("http://partner.dev.sedsy.com/table/query")
            .with_params(
                **{
                    "page": "1",
                    "limit": "10",
                    "tableCode": "",
                    "tableStatus": "",
                    "box": "",
                    "_": "1648106592994",
                }
            )
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "token": "24c7eadf81ca7de570d3f861814cd238",
                    "requestId": "20220324152312995859507",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.msg", "SUCCESS")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/fileUpload/getImg")
            .get("http://partner.dev.sedsy.com/fileUpload/getImg")
            .with_params(**{"fdfsId": "", "token": "24c7eadf81ca7de570d3f861814cd238"})
            .with_headers(
                **{
                    "Host": "partner.dev.sedsy.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Referer": "http://partner.dev.sedsy.com/modules/merchant/tablemanagement.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "mailver=mail; isAllwayHttps=0",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(**{"mailver": "mail", "isAllwayHttps": "0"})
            .validate()
            .assert_equal("status_code", 200)
        )
    ]


if __name__ == "__main__":
    TestCaseAddtable().test_start()
